# -*- coding: utf-8 -*-
"""Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dhMl5AiuOJRo0gDGqAUWLc2fXhjL_Kj
"""

#Importing all Necessary Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
import warnings
import joblib
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

"""Loading and Cleaning data"""

data = pd.read_csv('CLOTHING DATA.csv')
df = pd.DataFrame(data)
df

df.info()

df.isnull().sum()

# Mode for categorical data
df['inventory_category'].fillna(df['inventory_category'].mode()[0], inplace=True)

df['colour'].fillna(df['colour'].mode()[0], inplace=True)

df.isnull().sum()

# Drop rows that has missing values
df = df.dropna(subset=['description', 'size', 'zone_name', 'store_name', 'year'])

df.isnull().sum()

"""ENCODING NON NUMERICAL"""

from sklearn.preprocessing import LabelEncoder

# Label Encoding
label_encoder = LabelEncoder()
df['description'] = label_encoder.fit_transform(df['description'])
df['inventory_category'] = label_encoder.fit_transform(df['inventory_category'])
df['colour'] = label_encoder.fit_transform(df['colour'])
df['zone_name'] = label_encoder.fit_transform(df['zone_name'])
df['store_name'] = label_encoder.fit_transform(df['store_name'])
df['size'] = label_encoder.fit_transform(df['size'])

df

# Convert 'Date' column to datetime format
df['transaction_date'] = pd.to_datetime(df['transaction_date'], dayfirst=True, errors='coerce')

# Check if there are invalid dates
if df['transaction_date'].isnull().any():
    print("Invalid dates detected. Please check your 'transaction_date' column.")
else:
    # Convert to numerical format (YYYYMMDD)
    df['Year'] = df['transaction_date'].dt.year.astype(int)
    df['Month'] = df['transaction_date'].dt.month
    df['Day'] = df['transaction_date'].dt.day
    df = pd.get_dummies(df, columns=['Year'], drop_first=True)

df

# Drop the original 'Date' column
df.drop(columns=['transaction_date'], inplace=True)

df

"""SPLIT DATA INTO TESTING AND TRAINING SET"""

from sklearn.model_selection import train_test_split

Y = df['inventory_category']
Y

X = df.drop('inventory_category',axis= 1)
X

X_train, X_test , Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=42)
X_train

X_test

# Apply SMOTE to handle class imbalance on the training set only
smote = SMOTE(random_state=42)
X_train_resampled, Y_train_resampled = smote.fit_resample(X_train, Y_train)

# Check the distribution of classes after SMOTE
print("Class distribution after SMOTE:", pd.Series(Y_train_resampled).value_counts())

from imblearn.under_sampling import RandomUnderSampler

# Undersample the majority class
rus = RandomUnderSampler(random_state=42)
X_resampled, Y_resampled = rus.fit_resample(X, Y)

# Check new class distribution
print(pd.Series(Y_resampled).value_counts())

"""**Create and Train the Model**"""

# Create and train the XGBoost model
model = XGBClassifier(random_state=42)
model.fit(X_train, Y_train)

#  predictions and evaluation of the the model
Y_pred = model.predict(X_test)